# .github/workflows/deploy.yml
name: CI/CD Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: -----BEGIN OPENSSH PRIVATE KEY-----
                              b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBgsycxZ6
                              FAoFLwtlVY/CA3AAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIGhoRWPP8zz/zAto
                              GF4gsPkcdYJalpoYmtLCIwPq6iQaAAAAoKd7ujEfPKJCHdvNBbRViI/NGnRvbcRfe1Ac4n
                              CXWff+AGOhzHYDGaMMrop4bqPLJlDJptZU5ELDpphVB85KRpsN5f2YHX1tVp666g854Ysd
                              8T4wmUZL1b7nMf3hfqqnNXH1FSK8WYrAoD2k4p4MlE4WRKwsJw4EiNhfutiicpzfhDODPI
                              XOICE71nibeKp5GiuDuya/8+wsjrbixqneNjg=
                              -----END OPENSSH PRIVATE KEY-----

    - name: Deploy to DigitalOcean VPS via SSH
      env:
        HOST_USER: root
        HOST_IP: ${{ secrets.HOST_IP }}
      run: |
        # 1. Copia los archivos del proyecto al VPS
        # La IP p√∫blica es 142.93.82.96.
        rsync -avz --exclude '.git' -e "ssh -o StrictHostKeyChecking=no" ./ ${HOST_USER}@${HOST_IP}:/root/mi-proyecto-cicd/
        
        # 2. Ejecuta el script de despliegue en el VPS
        ssh ${HOST_USER}@${HOST_IP} "cd /root/mi-proyecto-cicd/ && chmod +x scripts/deploy.sh && sudo scripts/deploy.sh"